# mysql-exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              value: "root:root@(mysql-service:3306)/"
          ports:
            - containerPort: 9104
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: default
spec:
  ports:
    - port: 9104
      targetPort: 9104
  selector:
    app: mysql-exporter