apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3R1ZGVudA==      # "student" en base64
  SPRING_DATASOURCE_PASSWORD: c3R1ZGVudDEyMw==  # "student123" en base64

